In [1]:
pip install django

Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement django (from versions: none)
ERROR: No matching distribution found for django


In [15]:
import numpy as np
A = np.matrix([[1,1,1,1,1,1],[0,0,0,0,3,0],[0,0,1,0,0,2],[0,0,0,0,0,0],[0,0,0,0,4,0],[0,0,0,0,0,0]])
print(A)
element = A[0] 
print(element)

[[1 1 1 1 1 1]
 [0 0 0 0 3 0]
 [0 0 1 0 0 2]
 [0 0 0 0 0 0]
 [0 0 0 0 4 0]
 [0 0 0 0 0 0]]
[[1 1 1 1 1 1]]
